### PR TITLE
Integrated nonfunctional dummy structure

### PR DESCRIPTION
**Pull request by tboerger**

### CODE REVIEW

**Comment by nlf** [comment]
LGTM for just a stub

**Comment by nlf** [comment]
also maybe we should look into making this a template somewhere so it can be copied as the base for future plugins?

**Comment by tboerger** [comment]
> also maybe we should look into making this a template somewhere so it can be copied as the base for future plugins?

Where should we put that? Maybe a generator subcommand for drone-cli? @bradrydzewski?

**Comment by jackspirou** [comment]
LGTM

**Pull request merged**
